In [25]:
import pandas as pd
import tkinter
import TkinterMapView

ModuleNotFoundError: No module named 'TkinterMapView'

In [15]:
dest_df = pd.read_csv('./Destinations.csv')
dest_df

,Destinations,country,region,Climate,Budget,Activity,Demographics,Duration,Cuisine,History,Natural Wonder,Accommodation,Language
0,Tokyo,Japan,East Asia,Temperate,High,Cultural,Solo,Long,Asian,Modern,Mountains,Luxury,Japanese
1,Ottawa,Canada,North America,Cold,Medium,Adventure,Family-friendly,Medium,European,Modern,Forests,Mid-range,English
2,Mexico City,Mexico,North America,Temperate,Low,Cultural,Senior,Short,Latin American,Ancient,Mountains,Budget,Spanish
3,Rome,Italy,Southern Europe,Temperate,High,Cultural,Solo,Medium,European,Ancient,Beaches,Luxury,Italian
4,Brasilia,Brazil,South America,Tropical,Low,Adventure,Family-friendly,Long,Latin American,Modern,Beaches,Budget,Portuguese
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Luxor,Egypt,North Africa,Desert,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
98,Aswan,Egypt,North Africa,Desert,Low,Cultural,Solo,Short,Middle Eastern,Ancient,Rivers,Budget,Arabic
99,Christchurch,New Zealand,Oceania,Temperate,Medium,Adventure,Family-friendly,Medium,Western,Modern,Cityscape,Mid-range,English
100,Queenstown,New Zealand,Oceania,Temperate,High,Adventure,Solo,Short,Western,Modern,Mountains,Luxury,English
101,Rotorua,New Zealand,Oceania,Temperate,Medium,Cultural,Family-friendly,Short,Western,Modern,Geothermal,Mid-range,English

In [18]:
# Create a set of unique features
features = set()
for _, row in dest_df.iterrows():
    for col in row.index:
        if col not in ['Destinations', 'country', 'region']:
            features.add(col)

# Create a dictionary to map features to their names
feature_dict = {feature: col.title() for feature in features}

# Print the features
features

{'Accommodation',
 'Activity',
 'Budget',
 'Climate',
 'Cuisine',
 'Demographics',
 'Duration',
 'History',
 'Language',
 'Natural Wonder'}

In [20]:
s = set()
s.update(dest_df['Budget'])
s
dest_df.shape

(102, 13)

In [28]:
my_dict = {
    'key1': [1, 2, 3],
    'key2': [4, 5, 6],
    'key3': [1, 2, 3],
    'key4': [7, 8, 9],
}
for f in my_dict:
    print(f)

key1
key2
key3
key4